version: 2
jobs:
  buildone:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Build One - Hello"
      - run: sleep 10
  buildtwo:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Build Two - Hello"
      - run: sleep 15

